# Generated by Django 4.0.3 on 2023-03-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Number')),
                ('gdp', models.DecimalField(decimal_places=0, default=0, max_digits=40, verbose_name='GDP')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Name')),
                ('continent', models.CharField(default='', max_length=200, verbose_name='Continent')),
                ('language', models.CharField(default='English', max_length=200, verbose_name='Language')),
                ('population', models.IntegerField(default=0, verbose_name='Population')),
                ('religion', models.CharField(default='', max_length=200, verbose_name='National_religion')),
                ('need_help_in', models.CharField(default='', max_length=100, verbose_name='Need_help_in')),
                ('description', models.JSONField(blank=True, null=True)),
                ('currency', models.CharField(default='', max_length=20, verbose_name='Currency')),
                ('location_lat', models.DecimalField(decimal_places=9, default=0.0, max_digits=14, verbose_name='Latitude')),
                ('location_lng', models.DecimalField(decimal_places=9, default=0.0, max_digits=14, verbose_name='Longitude')),
                ('national_emergency', models.CharField(default='None', max_length=100, verbose_name='National_Emergency')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ImageField(upload_to='graphs/')),
                ('country', models.CharField(max_length=75)),
                ('file_index', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Percentile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentile', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentile')),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='platforms')),
                ('un_goals', models.CharField(choices=[('1) No Poverty', 'https://sdgs.un.org/goals/goal1'), ('2) Zero Hunger', 'https://sdgs.un.org/goals/goal2'), ('3) Good Health and Well-Being', 'https://sdgs.un.org/goals/goal3'), ('4) Quality Education', 'https://sdgs.un.org/goals/goal4'), ('5) Gender Equality', 'https://sdgs.un.org/goals/goal5'), ('6) Clean Water and Sanitation', 'https://sdgs.un.org/goals/goal6'), ('7) Affordable and Clean Energy', 'https://sdgs.un.org/goals/goal7'), ('8) Decent Work and Economic Growth', 'https://sdgs.un.org/goals/goal8'), ('9) Industry, Innovation and Infrastructure', 'https://sdgs.un.org/goals/goal9'), ('10) Reduced Inequalities', 'https://sdgs.un.org/goals/goal10'), ('11) Sustainable Cities and Communities', 'https://sdgs.un.org/goals/goal11'), ('12) Responsible Consumption and Production', 'https://sdgs.un.org/goals/goal12'), ('13) Climate Change', 'https://sdgs.un.org/goals/goal13'), ('14) Life Below Water', 'https://sdgs.un.org/goals/goal14'), ('15) Life on Land', 'https://sdgs.un.org/goals/goal15'), ('16) Peace, Justice and Strong Institutions', 'https://sdgs.un.org/goals/goal16'), ('17) Partnerships for the Goals', 'https://sdgs.un.org/goals/goal17')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('un_goal', models.IntegerField(choices=[(1, 'No Poverty'), (2, 'Zero Hunger'), (3, 'Good Health and Well-Being'), (4, 'Quality Education'), (5, 'Gender Equality'), (6, 'Clean Water and Sanitation'), (7, 'Affordable and Clean Energy'), (8, 'Decent Work and Economic Growth'), (9, 'Industry, Innovation and Infrastructure'), (10, 'Reduced Inequalities'), (11, 'Sustainable Cities and Communities'), (12, 'Responsible Consumption and Production'), (13, 'Climate Change'), (14, 'Life Below Water'), (15, 'Life on Land'), (16, 'Peace, Justice and Strong Institutions'), (17, 'Partnerships for the Goals')])),
                ('ngo_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0, verbose_name='Number')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_index', models.CharField(max_length=100, verbose_name='File_index')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
                ('currency', models.CharField(max_length=50, verbose_name='Currency')),
                ('currency_abbreviation', models.CharField(max_length=10, verbose_name='Currency_abbreviation')),
                ('ppp_log', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='PPP_log')),
                ('forex_score', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Forex_score')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Final_score')),
                ('gdp', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='GDP_per_capita')),
                ('gdp_ppp', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='GDP_per_capita_PPP')),
                ('coffee', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='coffee')),
                ('today_rate', models.DecimalField(decimal_places=6, default=0, max_digits=30, verbose_name='today_rate')),
                ('country_id', models.IntegerField(verbose_name='country_id')),
                ('rank', models.IntegerField(default=0, verbose_name='id')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('result', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('un_17', models.TextField(max_length=100)),
            ],
        ),
    ]
