# Generated by Django 4.0.3 on 2023-03-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_results_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='platforms')),
                ('un_goals', models.CharField(choices=[('1) No Poverty', 'https://sdgs.un.org/goals/goal1'), ('2) Zero Hunger', 'https://sdgs.un.org/goals/goal2'), ('3) Good Health and Well-Being', 'https://sdgs.un.org/goals/goal3'), ('4) Quality Education', 'https://sdgs.un.org/goals/goal4'), ('5) Gender Equality', 'https://sdgs.un.org/goals/goal5'), ('6) Clean Water and Sanitation', 'https://sdgs.un.org/goals/goal6'), ('7) Affordable and Clean Energy', 'https://sdgs.un.org/goals/goal7'), ('8) Decent Work and Economic Growth', 'https://sdgs.un.org/goals/goal8'), ('9) Industry, Innovation and Infrastructure', 'https://sdgs.un.org/goals/goal9'), ('10) Reduced Inequalities', 'https://sdgs.un.org/goals/goal10'), ('11) Sustainable Cities and Communities', 'https://sdgs.un.org/goals/goal11'), ('12) Responsible Consumption and Production', 'https://sdgs.un.org/goals/goal12'), ('13) Climate Change', 'https://sdgs.un.org/goals/goal13'), ('14) Life Below Water', 'https://sdgs.un.org/goals/goal14'), ('15) Life on Land', 'https://sdgs.un.org/goals/goal15'), ('16) Peace, Justice and Strong Institutions', 'https://sdgs.un.org/goals/goal16'), ('17) Partnerships for the Goals', 'https://sdgs.un.org/goals/goal17')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='countries')),
                ('platforms', models.ManyToManyField(to='api.platforms')),
            ],
        ),
    ]
