# Generated by Django 4.0.3 on 2023-03-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_platforms_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='image',
        ),
        migrations.RemoveField(
            model_name='country',
            name='platforms',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
        ),
    ]
