# Generated by Django 4.0.3 on 2023-03-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_country_description_remove_country_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='location_lat',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=14, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='country',
            name='location_lng',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=14, verbose_name='Longitude'),
        ),
    ]
