# Generated by Django 4.0.3 on 2023-03-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_country_continent_country_gdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='gdp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=99, verbose_name='GDP'),
        ),
    ]
