# Generated by Django 4.0.3 on 2023-03-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_country_gdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='gdp',
            field=models.IntegerField(default=0, verbose_name='GDP'),
        ),
    ]
