# Generated by Django 4.0.3 on 2023-03-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_country_gdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='gdp',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=40, verbose_name='GDP'),
        ),
    ]
