# Generated by Django 4.0.3 on 2023-03-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_country_language_country_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='need_help_in',
            field=models.CharField(default='', max_length=100, verbose_name='Need_help_in'),
        ),
        migrations.AddField(
            model_name='country',
            name='religion',
            field=models.CharField(default='', max_length=200, verbose_name='National_religion'),
        ),
    ]
