# Generated by Django 4.0.3 on 2023-03-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_country_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.JSONField(default=''),
        ),
    ]
