# Generated by Django 4.0.3 on 2023-03-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_country_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
