# Generated by Django 4.0.3 on 2023-03-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_percentile_remove_results_percentile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentile',
            name='percentile',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentile'),
        ),
    ]
