# Generated by Django 4.0.3 on 2023-03-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_results_gdp_results_gdp_ppp'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Number'),
        ),
    ]
