# Generated by Django 4.0.3 on 2023-03-25 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_results_file_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ngo',
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='ngo_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CountryName',
        ),
        migrations.DeleteModel(
            name='NGO',
        ),
    ]
