# Generated by Django 4.0.3 on 2023-03-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_ngo_country_remove_project_ngo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ImageField(upload_to='graphs/')),
                ('country', models.CharField(max_length=75)),
                ('file_index', models.CharField(max_length=50)),
            ],
        ),
    ]
