# Generated by Django 4.0.3 on 2023-03-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_results_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='number',
            new_name='Number',
        ),
    ]
