# Generated by Django 4.0.3 on 2023-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_number_country_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='const',
            field=models.IntegerField(default=0, verbose_name='const'),
        ),
    ]
