# Generated by Django 4.0.3 on 2023-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_number_country_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='Number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='country',
            name='national_emergency',
            field=models.CharField(default='None', max_length=100, verbose_name='National_Emergency'),
        ),
    ]
