# Generated by Django 4.0.3 on 2023-03-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_number_country_number_remove_country_const_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Number'),
        ),
    ]
